# Generated by Django 4.1.7 on 2023-03-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('progress', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
